server:
  port: 8082
spring:
  ai:
    mcp:
      server:
        enabled: true
        name: spring-ai-mcp-server-sse
        type: async
  mail:
    host: smtp.163.com               # 邮箱host
    port: 465                      # 邮箱固定端口
    username: 17347690192@163.com
    password: YQvfCKTNpdbYEhPp
    protocol: smtp                  # 邮箱协议
    default-encoding: UTF-8         # 默认编码
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://14.103.163.15:3306/springai-rag-mcp-dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 'R*@:/a3~TOE(*OJu@N6Njb(>%BY6v5&d'
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5